-- MySQL Script generated by MySQL Workbench
-- 10/26/15 20:49:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bibliotecamusical
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotecamusical
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecamusical` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bibliotecamusical` ;

-- -----------------------------------------------------
-- Table `bibliotecamusical`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecamusical`.`genero` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecamusical`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecamusical`.`artista` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `genero_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_artista_genero_idx` (`genero_id` ASC)  COMMENT '',
  CONSTRAINT `fk_artista_genero`
    FOREIGN KEY (`genero_id`)
    REFERENCES `bibliotecamusical`.`genero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecamusical`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecamusical`.`album` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `ano` INT NULL COMMENT '',
  `artista_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_album_artista1_idx` (`artista_id` ASC)  COMMENT '',
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `bibliotecamusical`.`artista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecamusical`.`musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecamusical`.`musica` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `nota` INT NULL COMMENT '',
  `duracao` INT NULL COMMENT '',
  `album_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_musica_album1_idx` (`album_id` ASC)  COMMENT '',
  CONSTRAINT `fk_musica_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `bibliotecamusical`.`album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
